<?php
$z[0]=Array("tpllang","",0,26);
$z[0][4]['name']="en";
$z[1]=Array("global","",109,138);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",282,307);
$z[2][4]['name']="cfg_phpurl";
$z[3]=Array("handlang","",386,402);
$z[4]=Array("lang","",534,553);
$z[4][4]['name']="search";
$z[5]=Array("lang","",637,657);
$z[5][4]['name']="langent";
$z[6]=Array("langlist","&nbsp; <a href='[field:typeurl/]'>[ [field:langname/] ]</a>",658,748);
$z[7]=Array("lang","",807,829);
$z[7][4]['name']="welcometo";
$z[8]=Array("channel"," <li class='home'><a href='[field:typeurl/]'>[field:lang.indexname/]</a></li> ",1096,1215);
$z[8][4]['get']="index";
$z[9]=Array("channel"," <li><a href='[field:typeurl/]'>[field:typename/]</a></li> ",1221,1320);
$z[9][4]['type']="top";

?>