<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",295,324);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",522,551);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("include","",634,672);
$z[3][4]['filename']="header.htm";
$z[4]=Array("lang","",728,752);
$z[4][4]['name']="currentpage";
$z[5]=Array("field","",753,782);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n                <li><span>[field:pubdate function=\"GetDateMK(@me)\"/]</span><a href='[field:arcurl/]'>[field:title/]</a></li>\r\n              	",1192,1388);
$z[6][4]['pagesize']="12";
$z[6][4]['listtype']="text";
$z[7]=Array("pagelist","",1456,1486);
$z[7][4]['listsize']="7";
$z[8]=Array("lang","",1892,1916);
$z[8][4]['name']="newscatalog";
$z[9]=Array("cattree","",2153,2182);
$z[10]=Array("lang","",2547,2564);
$z[10][4]['name']="news";
$z[11]=Array("list","\r\n                  <li><a href='[field:arcurl/]'>[field:title/]</a></li>\r\n                  ",2811,2950);
$z[11][4]['row']="12";
$z[11][4]['titlelen']="40";
$z[12]=Array("include","",3223,3261);
$z[12][4]['filename']="footer.htm";

?>