<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",295,324);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",425,450);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",611,640);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",945,983);
$z[4][4]['filename']="header.htm";
$z[5]=Array("lang","",1041,1065);
$z[5][4]['name']="currentpage";
$z[6]=Array("field","",1066,1095);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n                <li>\r\n                  <dl>\r\n                    <dt><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img src='[field:litpic/]' /></a></dt>\r\n                    <dd class=\"textCenter\" ><strong><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></strong></dd>\r\n                    <dd>[field:lang.standard/] <em>[field:psize /]</em></dd>\r\n                    <dd>[field:lang.brand/] <em>[field:brand /]</em> </dd>\r\n                  </dl>\r\n                </li>\r\n                ",1489,2037);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",2133,2163);
$z[8][4]['listsize']="7";
$z[9]=Array("lang","",2569,2596);
$z[9][4]['name']="productcatalog";
$z[10]=Array("cattree","",2833,2862);
$z[11]=Array("lang","",3227,3250);
$z[11][4]['name']="newproduct";
$z[12]=Array("arclist","\r\n                  <li><a href='[field:arcurl/]'>[field:title/]</a></li>\r\n                  ",3497,3642);
$z[12][4]['row']="10";
$z[12][4]['titlelen']="40";
$z[13]=Array("include","",3915,3953);
$z[13][4]['filename']="footer.htm";

?>