<?php
$z[0]=Array("global","",76,104);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("wintitle","",115,131);
$z[2]=Array("global","",186,220);
$z[2][4]['name']="cfg_plus_dir";
$z[3]=Array("global","",264,291);
$z[3][4]['name']="cfg_plus_dir";
$z[4]=Array("global","",510,544);
$z[4][4]['name']="cfg_plus_dir";
$z[5]=Array("wecome_info","",574,593);
$z[6]=Array("global","",703,725);
$z[6][4]['name']="winform";
$z[7]=Array("lang_cms_powerby","",777,801);

?>