<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",295,324);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",522,551);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("include","",634,672);
$z[3][4]['filename']="header.htm";
$z[4]=Array("lang","",728,752);
$z[4][4]['name']="currentpage";
$z[5]=Array("field","",753,782);
$z[5][4]['name']="position";
$z[6]=Array("field","",1189,1211);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1320,1349);
$z[7][4]['name']="content";
$z[8]=Array("lang","",1747,1767);
$z[8][4]['name']="aboutus";
$z[9]=Array("channel","<li><a href='[field:typeurl/]'>[field:typename/]</a></li>",2014,2111);
$z[9][4]['get']="page";
$z[10]=Array("include","",2365,2403);
$z[10][4]['filename']="footer.htm";

?>